### ISSUE TITLE
How to derive the from address of a decoded transaction?

### ISSUE THREAD

**Issue by Undead8** [tharsis/evmosjs#25]
The [bytesToLegacyTx](https://github.com/tharsis/evmosjs/blob/55dc1dc340a3c9c842803f502d480968a10ddb85/packages/proto/src/messages/msgEthereumTx.ts#L7) function does not return the from address of the decoded transaction (see #16). How can the from address be derived from the result?

The encoded transaction below corresponds to [this one](https://cronoscan.com/tx/0xd82d4fe7ac3c73d6394920ede94536d2f34fe6101a9cec9741fc792358c69f5d) on the block explorer.
`"CpgDCuQCCh8vZXRoZXJtaW50LmV2bS52MS5Nc2dFdGhlcmV1bVR4EsACCvABChovZXRoZXJtaW50LmV2bS52MS5MZWdhY3lUeBLRAQgBEg01MDAwMDAwMDAwMDAwGP3wAiIqMHhEQzViQkRiNEE0YjA1MUJEQjg1Qjk1OWVCM2NCRDFjOEMwZDBjMTA1KgEwMkSiLLRlAAAAAAAAAAAAAAAAejzbI2T5I2mmAsroEWfQZ5CH5qMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAToBVUIgLB9VIqNf1ehvCU+duvAioON8KnG/dm6uyCXm5ftj6G5KIAfE/UfA1uCbKVxlsqYWPgu22ORLlm0aGC3CiKawhcmJEQAAAAAAgGVAGkIweGQ4MmQ0ZmU3YWMzYzczZDYzOTQ5MjBlZGU5NDUzNmQyZjM0ZmU2MTAxYTljZWM5NzQxZmM3OTIzNThjNjlmNWT6Py4KLC9ldGhlcm1pbnQuZXZtLnYxLkV4dGVuc2lvbk9wdGlvbnNFdGhlcmV1bVR4EiUSIwodCgdiYXNlY3JvEhIyMzYxNDUwMDAwMDAwMDAwMDAQ/fAC"`

Thanks @hanchon

**Comment by hanchon** [comment]
I just added the example on the proto package, let me know if that works for you!
https://github.com/tharsis/evmosjs/blob/main/packages/proto/example/protoTransactionToEthTransaction.md

**Comment by Undead8** [comment]
@hanchon Works great, thanks a lot!
